<?php


namespace app\controllers;


use yii\web\Controller;
use yii\web\Response;

class MainController extends Controller
{


    public $enableCsrfValidation=false;

    public function actions()
    {
        \Yii::$app->response->headers->add('Access-Control-Allow-Origin','*');
        return parent::actions(); // TODO: Change the autogenerated stub
    }


    public function beforeAction($action)
    {
        \Yii::$app->response->format=Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}